apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  labels:
    app: todo-backend
spec:
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: todo-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: MONGO_INITDB_PORT
              value: "27017"
            - name: MONGO_INITDB_HOST
              value: todo-db
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: password
            - name: REDIS_HOST
              value: todo-redis
            - name: REDIS_PORT
              value: "6379"
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"