apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  labels:
    run: todo-backend
spec:
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: todo-backend
  type: ClusterIP